name: NodeJS with Gulp

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 18.x
      uses: actions/setup-node@v1
      with:
        node-version: 18.x
    - name: Build
      run: |
        yarn install --immutable
        yarn build
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4
      with:
        branch: gh-pages
        folder: dist

